nome = input('Digite seu nome:')
print('Prazer em conhece-lo {}!'.format(nome))
print('Prazer em conhece-lo {:20} !'.format(nome))
print('Prazer em conhece-lo {:>20} !'.format(nome))
print('Prazer em conhece-lo {:<20} !'.format(nome))
print('Prazer em conhece-lo {:^20} !'.format(nome))
print('Prazer em conhece-lo {:=^20} !'.format(nome))